version: '3.8'

services:
  frontend:
    build: 
      context: ./Frontend  # Path to the directory containing the Dockerfile for the frontend
      dockerfile: Dockerfile  # Optional, defaults to Dockerfile if the filename matches
    ports:
      - "3001:3001"  # Frontend accessible on localhost:3001
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Ensure the path is correct
    ports:
      - "9090:9090"  # Prometheus accessible on localhost:3000
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Grafana accessible on localhost:3002
    volumes:
      - ./Grafana:/var/lib/grafana  # Persistent volume for Grafana data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge
